[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAME-ORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Permitted-Cross-Domain-Policies = "none"
    Referrer-Policy = "SAME-ORIGIN"
    # Content-Security-Policy = "frame-ancestors https://www.facebook.com"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
