[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# TODO: add headers, set 404
# /*
#   Strict-Transport-Security: max-age=63072000; includeSubDomains; preload;
  
#   X-Frame-Options: DENY
#   X-XSS-Protection: 1; mode=block
#   X-Content-Type-Options: nosniff
#   X-Permitted-Cross-Domain-Policies: none
#   Referrer-Policy: no-referrer
